set(BENNU_REQUIRED_TUP_TRACEABILITY_ROWS
  [=[BENNU-SPEC-0006 section 4 structural type arena equality ownership notation and overflow|tests/tuple_foundation_conformance.cpp|TUP-002-TYPES]=]
  [=[BENNU-SPEC-0006 sections 5.1 5.4 and 5.6 flat values validation and queries|tests/tuple_foundation_conformance.cpp|TUP-003-VALUES]=]
  [=[BENNU-SPEC-0006 sections 5.2 5.3 and 5.5 unique transfer borrow lifetime detachment and reverse cleanup|tests/tuple_foundation_conformance.cpp|TUP-004-MOVE-CLEANUP]=]
  [=[BENNU-SPEC-0006 sections 4.1 7.3 and 10 iterative canonical formatting|tests/tuple_foundation_conformance.cpp|TUP-005-FORMAT]=]
  [=[BENNU-SPEC-0006 section 6.1 profile-v2 identities and v1 refusal|tests/tuple_foundation_conformance.cpp|TUP-006-PROFILE-IDENTITY]=]
  [=[BENNU-SPEC-0006 sections 6.2 through 6.4 canonical tuple-table accounting|tests/tuple_foundation_conformance.cpp|TUP-007-TABLE-CHARGE]=]
  [=[BENNU-SPEC-0006 section 6.5 allocation-failure ordinals|tests/tuple_foundation_conformance.cpp|TUP-008-ALLOCATION-ORDINAL]=]
  [=[BENNU-SPEC-0006 section 7 construction sequencing admission and failure cleanup|tests/tuple_foundation_conformance.cpp|TUP-009-CONSTRUCTION]=]
  [=[BENNU-SPEC-0006 section 8.3 public direct tuple preservation|tests/tuple_foundation_conformance.cpp|TUP-012-DIRECT-PRESERVATION]=]
  [=[BENNU-SPEC-0006 section 10 deep reduced-stack traversal failure cleanup and overflow|tests/tuple_foundation_conformance.cpp|TUP-016-DEEP-NESTING]=]
  [=[BENNU-SPEC-0006 section 13 CLI emitted native profile and platform regression|tests/public_resource_contract.cmake|TUP-018-REGRESSION-PLATFORMS]=]
  [=[BENNU-SPEC-0006 sections 3 9.1 and 11.1 tuple grammar flat arenas and exact provenance|src/rewrite.cpp|TUP-001-GRAMMAR]=]
  [=[BENNU-SPEC-0006 sections 4 6.1 6.2 and 7.3 literal types canonical values and profile-v2|src/rewrite.cpp|TUP-050-EVALUATOR-FORMAT-PROFILE]=]
  [=[BENNU-SPEC-0006 sections 6.5 7.1 7.2 and 7.3 literal allocation failure cleanup|src/rewrite.cpp|TUP-050-FAULT-TRANSACTION]=]
  [=[BENNU-SPEC-0006 section 8.3 source direct calls preserve one tuple argument|src/rewrite.cpp|TUP-050-DIRECT-PRESERVATION]=]
  [=[BENNU-SPEC-0006 sections 5 6 7 10 and 13 deterministic strict C11 and native tuple agreement|tests/tuple_literal_contract.cmake|TUP-017-STRICT-C-NATIVE]=]
  [=[BENNU-SPEC-0006 sections 8.1 8.2 and 8.4 static one-level prefix expansion and ordering|src/rewrite.cpp|TUP-010-STATIC-SPREAD]=]
  [=[BENNU-SPEC-0006 sections 8.2 and 7.3 borrowed spread execution and transactional release|src/rewrite.cpp|TUP-011-SPREAD-RUNTIME]=]
  [=[BENNU-SPEC-0006 section 9 semantic argument provenance for literal and computed tuple elements|src/rewrite.cpp|TUP-013-PROVENANCE]=]
  [=[BENNU-SPEC-0006 sections 8 through 10 evaluator strict C11 and native prefix-spread agreement|tests/tuple_literal_contract.cmake|TUP-051-STRICT-C-NATIVE]=]
)
