if(NOT DEFINED BENNU_SOURCE_DIR)
  message(FATAL_ERROR "BENNU_SOURCE_DIR is required")
endif()

set(record "${BENNU_SOURCE_DIR}/tests/spec-traceability.tsv")
file(STRINGS "${record}" rows)
set(requirement_count 0)
foreach(row IN LISTS rows)
  if(row STREQUAL "" OR row MATCHES "^#")
    continue()
  endif()
  string(REPLACE "|" ";" fields "${row}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 3)
    message(FATAL_ERROR "malformed traceability row: ${row}")
  endif()
  list(GET fields 0 requirement)
  list(GET fields 1 relative_source)
  list(GET fields 2 identifier)
  set(source "${BENNU_SOURCE_DIR}/${relative_source}")
  if(NOT EXISTS "${source}")
    message(FATAL_ERROR "${requirement}: missing test source ${relative_source}")
  endif()
  file(READ "${source}" source_text)
  string(FIND "${source_text}" "${identifier}" identifier_at)
  if(identifier_at EQUAL -1)
    message(FATAL_ERROR
      "${requirement}: stale test identifier '${identifier}' in ${relative_source}")
  endif()
  math(EXPR requirement_count "${requirement_count} + 1")
endforeach()

if(requirement_count LESS 30)
  message(FATAL_ERROR
    "traceability record is incomplete: only ${requirement_count} requirements")
endif()
